# docker/docker-compose.yml
version: "3.9"
services:
  coral_mobilenet:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: coral_mobilenet

    ## 1) 카메라 노드와 메모리 풀 전체 전달
    privileged: true          # capabilities + cgroup rules

    devices:
      - /dev/bus/usb          # /dev 전체 대신 USB 만도 OK
    # devices:
    #   - "/dev:/dev"           # ← /dev 전체를 그대로 넘겨도 되고,
    #  또는 필요한 노드만 나열:
    #  - "/dev/vchiq:/dev/vchiq"
    #  - "/dev/video0:/dev/video0"
    #  - "/dev/media0:/dev/media0"
    #  - "/dev/v4l-subdev0:/dev/v4l-subdev0"
    #  - "/dev/dma_heap:/dev/dma_heap"

    ## 2) udev 이벤트 전달
    volumes:
      - /dev/bus/usb:/dev/bus/usb   # /dev/bus/usb 전체를 볼륨으로 마운트
      - /run/udev:/run/udev:ro   # ★ 중요
      - /mnt/usb:/workspace/dataset
      - ./:/workspace

    ## 3) 성능/메모리
    tmpfs:
      - /dev/shm:size=64m,exec   # libcamera-vid 의 DMA 버퍼가 /dev/shm 사용

    group_add:
      - plugdev

    command: ["python", "-u", "inference.py"]   # -u: 버퍼링 OFF
    restart: unless-stopped
